# Generated by Django 2.1.2 on 2019-02-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=3)),
                ('elevation_control', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('z', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('true_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('true_elevation', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('beach_name', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('mhhw', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mllw', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='survey_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
    ]
