# Generated by Django 2.1.2 on 2019-02-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190221_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='true_distance',
        ),
        migrations.RemoveField(
            model_name='station',
            name='true_elevation',
        ),
    ]
