# Generated by Django 2.1.2 on 2018-11-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20181107_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='survey_instance',
            new_name='survey_instance_id',
        ),
    ]
